

# Define the sectors
sectors = [
    "Information Technology (IT)",
    "Banking & Financial Services (BFSI)",
    "Pharmaceuticals & Healthcare",
    "Automobiles",
    "Oil & Gas",
    "Fast-Moving Consumer Goods (FMCG)",
    "Metals & Mining",
    "Power & Utilities",
    "Telecom",
    "Real Estate & Construction",
    "Infrastructure",
    "Chemicals & Specialty Chemicals",
    "Consumer Durables",
    "Textiles",
    "Cement & Building Materials",
    "Logistics",
    "Media & Entertainment",
    "Hospitality & Tourism",
    "Renewable Energy",
    "Electric Vehicles (EVs)",
    "Agriculture & Agrochemicals",
    "Aviation",
    "Defence & Aerospace",
    "Sugar & Fertilizers",
    "Capital Goods",
    "others"
]

# Heuristic mapping of keywords to sectors
sector_keywords = {
    "Information Technology (IT)": ["TECH", "SOFT", "SOL", "INFO", "DATA", "DIGI", "SYST", "NET", "WEB", "CLOUD", "AI",
                                    "IT", "COMPU"],
    "Banking & Financial Services (BFSI)": ["BANK", "FIN", "HFC", "CAPITAL", "INVEST", "SECUR", "INSUR", "CREDIT",
                                            "LIFE", "AMC", "FUND", "LOAN", "MUTUAL"],
    "Pharmaceuticals & Healthcare": ["PHARM", "LIFE", "HEALTH", "MED", "BIO", "CARE", "HOSP", "DRUG", "DIAG", "CLIN",
                                     "SURG", "WELL"],
    "Automobiles": ["AUTO", "MOTOR", "VEHICLE", "TIRE", "TYRE", "CAR", "BIKE", "EICHER", "HERO", "TVS"],
    "Oil & Gas": ["OIL", "GAS", "PETRO", "FUEL", "REFIN", "LNG", "ONGC", "HINDPETRO", "IOC"],
    "Fast-Moving Consumer Goods (FMCG)": ["CONSUM", "FOOD", "BRIT", "AGRO", "DAIRY", "BEVER", "NESTLE", "HUL", "DABUR",
                                          "MARICO"],
    "Metals & Mining": ["METAL", "MIN", "ALUM", "COPPER", "STEEL", "IRON", "GOLD", "ZINC", "VEDL", "HINDALCO"],
    "Power & Utilities": ["POWER", "ENERGY", "ELECT", "UTILI", "GRID", "NTPC", "NHPC", "TORNTPOWER", "ADANI POWER"],
    "Telecom": ["TELECOM", "COMM", "VIANET", "IDEA", "AIRTEL", "TATA COMM"],
    "Real Estate & Construction": ["REAL", "ESTATE", "HOUS", "BUILD", "PROP", "CONSTR", "INFRA", "DEV", "HOUSING"],
    "Infrastructure": ["INFRA", "CONSTR", "ENGIN", "PROJ", "ROAD", "HIGHWAY", "BRIDGE", "PORT", "RVNL", "IRCON"],
    "Chemicals & Specialty Chemicals": ["CHEM", "SPEC", "SOLV", "POLY", "FERT", "PLAST", "RESIN", "ALKALI", "VINYL",
                                        "PIGMENT"],
    "Consumer Durables": ["DURAB", "APPLI", "FURN", "KITCH", "WHIRL", "HAVELL", "CROMPTON"],
    "Textiles": ["TEXT", "FABR", "COTTON", "SILK", "YARN", "WEAV", "GARMENT", "FASH"],
    "Cement & Building Materials": ["CEMENT", "CONCR", "TILE", "CERAM", "PLY", "ASBEST", "GRANITE", "ULTRATECH"],
    "Logistics": ["LOGIST", "SHIP", "CARGO", "TRANS", "PORT", "SUPPLY", "DELIV", "COURIER"],
    "Media & Entertainment": ["MEDIA", "ENTERT", "NEWS", "TV", "RADIO", "FILM", "MUSIC", "ADVERT", "DIGITAL"],
    "Hospitality & Tourism": ["HOTEL", "RESORT", "TOUR", "TRAVEL", "HOSPIT", "LEISURE", "LODG"],
    "Renewable Energy": ["RENEW", "SOLAR", "WIND", "GREEN", "CLEAN", "ECO", "SUZLON"],
    "Electric Vehicles (EVs)": ["ELECTRIC", "EV", "BATT", "LITHIUM", "CHARG", "MOBIL", "AUTO"],
    "Agriculture & Agrochemicals": ["AGRI", "FARM", "CROP", "FERTIL", "SEED", "PEST", "IRRIG", "TRACTOR"],
    "Aviation": ["AVIAT", "AIR", "FLIGHT", "AERO", "JET", "INDIGO"],
    "Defence & Aerospace": ["DEFEN", "AERO", "ARMS", "NAVAL", "MISSILE", "RADAR", "ELECTRON", "BDL", "HAL"],
    "Sugar & Fertilizers": ["SUGAR", "FERTIL", "KHET", "URVAR", "CROP", "NUTRI"],
    "Capital Goods": ["CAPITAL", "ENGIN", "MACH", "EQUIP", "TOOL", "INDU", "BEAR", "VALV", "PIPE", "PREC"],
}

# Original Nifty 500 symbols
nifty_500_symbols = ["360ONE.NS", "3MINDIA.NS", "ABB.NS", "ACC.NS", "AIAENG.NS", "APLAPOLLO.NS", "AUBANK.NS",
                     "AADHARHFC.NS", "AARTIIND.NS", "AAVAS.NS", "ABBOTINDIA.NS", "ACE.NS", "ADANIENSOL.NS",
                     "ADANIENT.NS", "ADANIGREEN.NS", "ADANIPORTS.NS", "ADANIPOWER.NS", "ATGL.NS", "AWL.NS",
                     "ABCAPITAL.NS", "ABFRL.NS", "ABREL.NS", "ABSLAMC.NS", "AEGISLOG.NS", "AFFLE.NS", "AJANTPHARM.NS",
                     "AKUMS.NS", "APLLTD.NS", "ALKEM.NS", "ALKYLAMINE.NS", "ALOKINDS.NS", "ARE&M.NS", "AMBER.NS",
                     "AMBUJACEM.NS", "ANANDRATHI.NS", "ANANTRAJ.NS", "ANGELONE.NS", "APARINDS.NS", "APOLLOHOSP.NS",
                     "APOLLOTYRE.NS", "APTUS.NS", "ACI.NS", "ASAHIINDIA.NS", "ASHOKLEY.NS", "ASIANPAINT.NS",
                     "ASTERDM.NS", "ASTRAZEN.NS", "ASTRAL.NS", "ATUL.NS", "AUROPHARMA.NS", "AVANTIFEED.NS", "DMART.NS",
                     "AXISBANK.NS", "BASF.NS", "BEML.NS", "BLS.NS", "BSE.NS", "BAJAJ-AUTO.NS", "BAJFINANCE.NS",
                     "BAJAJFINSV.NS", "BAJAJHLDNG.NS", "BALAMINES.NS", "BALKRISIND.NS", "BALRAMCHIN.NS",
                     "BANDHANBNK.NS", "BANKBARODA.NS", "BANKINDIA.NS", "MAHABANK.NS", "BATAINDIA.NS", "BAYERCROP.NS",
                     "BERGEPAINT.NS", "BDL.NS", "BEL.NS", "BHARATFORG.NS", "BHEL.NS", "BPCL.NS", "BHARTIARTL.NS",
                     "BHARTIHEXA.NS", "BIKAJI.NS", "BIOCON.NS", "BIRLACORPN.NS", "BSOFT.NS", "BLUEDART.NS",
                     "BLUESTARCO.NS", "BBTC.NS", "BOSCHLTD.NS", "BRIGADE.NS", "BRITANNIA.NS", "MAPMYINDIA.NS", "CCL.NS",
                     "CESC.NS", "CGPOWER.NS", "CIEINDIA.NS", "CRISIL.NS", "CAMPUS.NS", "CANFINHOME.NS", "CANBK.NS",
                     "CAPLIPOINT.NS", "CGCL.NS", "CARBORUNIV.NS", "CASTROLIND.NS", "CEATLTD.NS", "CELLO.NS",
                     "CENTRALBK.NS", "CDSL.NS", "CENTURYPLY.NS", "CERA.NS", "CHALET.NS", "CHAMBLFERT.NS",
                     "CHEMPLASTS.NS", "CHENNPETRO.NS", "CHOLAHLDNG.NS", "CHOLAFIN.NS", "CIPLA.NS", "CUB.NS", "CLEAN.NS",
                     "COALINDIA.NS", "COCHINSHIP.NS", "COFORGE.NS", "COLPAL.NS", "CAMS.NS", "CONCORDBIO.NS",
                     "CONCOR.NS", "COROMANDEL.NS", "CRAFTSMAN.NS", "CREDITACC.NS", "CROMPTON.NS", "CUMMINSIND.NS",
                     "CYIENT.NS", "DLF.NS", "DOMS.NS", "DABUR.NS", "DALBHARAT.NS", "DATAPATTNS.NS", "DEEPAKFERT.NS",
                     "DEEPAKNTR.NS", "DELHIVERY.NS", "DEVYANI.NS", "DIVISLAB.NS", "DIXON.NS", "LALPATHLAB.NS",
                     "DRREDDY.NS", "EIDPARRY.NS", "EIHOTEL.NS", "EASEMYTRIP.NS", "EICHERMOT.NS", "ELECON.NS",
                     "ELGIEQUIP.NS", "EMAMILTD.NS", "EMCURE.NS", "ENDURANCE.NS", "ENGINERSIN.NS", "EQUITASBNK.NS",
                     "ERIS.NS", "ESCORTS.NS", "EXIDEIND.NS", "NYKAA.NS", "FEDERALBNK.NS", "FACT.NS", "FINEORG.NS",
                     "FINCABLES.NS", "FINPIPE.NS", "FSL.NS", "FIVESTAR.NS", "FORTIS.NS", "GRINFRA.NS", "GAIL.NS",
                     "GVT&D.NS", "GMRAIRPORT.NS", "GRSE.NS", "GICRE.NS", "GILLETTE.NS", "GLAND.NS", "GLAXO.NS",
                     "GLENMARK.NS", "MEDANTA.NS", "GODIGIT.NS", "GPIL.NS", "GODFRYPHLP.NS", "GODREJAGRO.NS",
                     "GODREJCP.NS", "GODREJIND.NS", "GODREJPROP.NS", "GRANULES.NS", "GRAPHITE.NS", "GRASIM.NS",
                     "GESHIP.NS", "GRINDWELL.NS", "GAEL.NS", "FLUOROCHEM.NS", "GUJGASLTD.NS", "GMDCLTD.NS", "GNFC.NS",
                     "GPPL.NS", "GSFC.NS", "GSPL.NS", "HEG.NS", "HBLENGINE.NS", "HCLTECH.NS", "HDFCAMC.NS",
                     "HDFCBANK.NS", "HDFCLIFE.NS", "HFCL.NS", "HAPPSTMNDS.NS", "HAVELLS.NS", "HEROMOTOCO.NS", "HSCL.NS",
                     "HINDALCO.NS", "HAL.NS", "HINDCOPPER.NS", "HINDPETRO.NS", "HINDUNILVR.NS", "HINDZINC.NS",
                     "POWERINDIA.NS", "HOMEFIRST.NS", "HONASA.NS", "HONAUT.NS", "HUDCO.NS", "ICICIBANK.NS",
                     "ICICIGI.NS", "ICICIPRULI.NS", "ISEC.NS", "IDBI.NS", "IDFCFIRSTB.NS", "IFCI.NS", "IIFL.NS",
                     "INOXINDIA.NS", "IRB.NS", "IRCON.NS", "ITCHOTELS.NS", "ITC.NS", "ITI.NS", "INDGN.NS",
                     "INDIACEM.NS", "INDIAMART.NS", "INDIANB.NS", "IEX.NS", "INDHOTEL.NS", "IOC.NS", "IOB.NS",
                     "IRCTC.NS", "IRFC.NS", "IREDA.NS", "IGL.NS", "INDUSTOWER.NS", "INDUSINDBK.NS", "NAUKRI.NS",
                     "INFY.NS", "INOXWIND.NS", "INTELLECT.NS", "INDIGO.NS", "IPCALAB.NS", "JBCHEPHARM.NS",
                     "JKCEMENT.NS", "JBMA.NS", "JKLAKSHMI.NS", "JKTYRE.NS", "JMFINANCIL.NS", "JSWENERGY.NS",
                     "JSWINFRA.NS", "JSWSTEEL.NS", "JPPOWER.NS", "J&KBANK.NS", "JINDALSAW.NS", "JSL.NS",
                     "JINDALSTEL.NS", "JIOFIN.NS", "JUBLFOOD.NS", "JUBLINGREA.NS", "JUBLPHARMA.NS", "JWL.NS",
                     "JUSTDIAL.NS", "JYOTHYLAB.NS", "JYOTICNC.NS", "KPRMILL.NS", "KEI.NS", "KNRCON.NS", "KPITTECH.NS",
                     "KSB.NS", "KAJARIACER.NS", "KPIL.NS", "KALYANKJIL.NS", "KANSAINER.NS", "KARURVYSYA.NS",
                     "KAYNES.NS", "KEC.NS", "KFINTECH.NS", "KIRLOSBROS.NS", "KIRLOSENG.NS", "KOTAKBANK.NS", "KIMS.NS",
                     "LTF.NS", "LTTS.NS", "LICHSGFIN.NS", "LTIM.NS", "LT.NS", "LATENTVIEW.NS", "LAURUSLABS.NS",
                     "LEMONTREE.NS", "LICI.NS", "LINDEINDIA.NS", "LLOYDSME.NS", "LUPIN.NS", "MMTC.NS", "MRF.NS",
                     "LODHA.NS", "MGL.NS", "MAHSEAMLES.NS", "M&MFIN.NS", "M&M.NS", "MAHLIFE.NS", "MANAPPURAM.NS",
                     "MRPL.NS", "MANKIND.NS", "MARICO.NS", "MARUTI.NS", "MASTEK.NS", "MFSL.NS", "MAXHEALTH.NS",
                     "MAZDOCK.NS", "METROBRAND.NS", "METROPOLIS.NS", "MINDACORP.NS", "MSUMI.NS", "MOTILALOFS.NS",
                     "MPHASIS.NS", "MCX.NS", "MUTHOOTFIN.NS", "NATCOPHARM.NS", "NBCC.NS", "NCC.NS", "NHPC.NS",
                     "NLCINDIA.NS", "NMDC.NS", "NSLNISP.NS", "NTPC.NS", "NH.NS", "NATIONALUM.NS", "NAVINFLUOR.NS",
                     "NESTLEIND.NS", "NETWEB.NS", "NETWORK18.NS", "NEWGEN.NS", "NAM-INDIA.NS", "NUVAMA.NS", "NUVOCO.NS",
                     "OBEROIRLTY.NS", "ONGC.NS", "OIL.NS", "OLECTRA.NS", "PAYTM.NS", "OFSS.NS", "POLICYBZR.NS",
                     "PCBL.NS", "PIIND.NS", "PNBHOUSING.NS", "PNCINFRA.NS", "PTCIL.NS", "PVRINOX.NS", "PAGEIND.NS",
                     "PATANJALI.NS", "PERSISTENT.NS", "PETRONET.NS", "PFIZER.NS", "PHOENIXLTD.NS", "PIDILITIND.NS",
                     "PEL.NS", "PPLPHARMA.NS", "POLYMED.NS", "POLYCAB.NS", "POONAWALLA.NS", "PFC.NS", "POWERGRID.NS",
                     "PRAJIND.NS", "PRESTIGE.NS", "PGHH.NS", "PNB.NS", "QUESS.NS", "RRKABEL.NS", "RBLBANK.NS",
                     "RECLTD.NS", "RHIM.NS", "RITES.NS", "RADICO.NS", "RVNL.NS", "RAILTEL.NS", "RAINBOW.NS",
                     "RAJESHEXPO.NS", "RKFORGE.NS", "RCF.NS", "RATNAMANI.NS", "RTNINDIA.NS", "RAYMOND.NS",
                     "REDINGTON.NS", "RELIANCE.NS", "ROUTE.NS", "SBFC.NS", "SBICARD.NS", "SBILIFE.NS", "SJVN.NS",
                     "SKFINDIA.NS", "SRF.NS", "SAMMAANCAP.NS", "MOTHERSON.NS", "SANOFI.NS", "SAPPHIRE.NS",
                     "SAREGAMA.NS", "SCHAEFFLER.NS", "SCHNEIDER.NS", "SCI.NS", "SHREECEM.NS", "RENUKA.NS",
                     "SHRIRAMFIN.NS", "SHYAMMETL.NS", "SIEMENS.NS", "SIGNATURE.NS", "SOBHA.NS", "SOLARINDS.NS",
                     "SONACOMS.NS", "SONATSOFTW.NS", "STARHEALTH.NS", "SBIN.NS", "SAIL.NS", "SWSOLAR.NS", "SUMICHEM.NS",
                     "SPARC.NS", "SUNPHARMA.NS", "SUNTV.NS", "SUNDARMFIN.NS", "SUNDRMFAST.NS", "SUPREMEIND.NS",
                     "SUVENPHAR.NS", "SUZLON.NS", "SWANENERGY.NS", "SYNGENE.NS", "SYRMA.NS", "TBOTEK.NS", "TVSMOTOR.NS",
                     "TVSSCS.NS", "TANLA.NS", "TATACHEM.NS", "TATACOMM.NS", "TCS.NS", "TATACONSUM.NS", "TATAELXSI.NS",
                     "TATAINVEST.NS", "TATAMOTORS.NS", "TATAPOWER.NS", "TATASTEEL.NS", "TATATECH.NS", "TTML.NS",
                     "TECHM.NS", "TECHNOE.NS", "TEJASNET.NS", "NIACL.NS", "RAMCOCEM.NS", "THERMAX.NS", "TIMKEN.NS",
                     "TITAGARH.NS", "TITAN.NS", "TORNTPHARM.NS", "TORNTPOWER.NS", "TRENT.NS", "TRIDENT.NS",
                     "TRIVENI.NS", "TRITURBINE.NS", "TIINDIA.NS", "UCOBANK.NS", "UNOMINDA.NS", "UPL.NS", "UTIAMC.NS",
                     "UJJIVANSFB.NS", "ULTRACEMCO.NS", "UNIONBANK.NS", "UBL.NS", "UNITDSPR.NS", "USHAMART.NS",
                     "VGUARD.NS", "VIPIND.NS", "DBREALTY.NS", "VTL.NS", "VARROC.NS", "VBL.NS", "MANYAVAR.NS", "VEDL.NS",
                     "VIJAYA.NS", "VINATIORGA.NS", "IDEA.NS", "VOLTAS.NS", "WELCORP.NS", "WELSPUNLIV.NS", "WESTLIFE.NS",
                     "WHIRLPOOL.NS", "WIPRO.NS", "YESBANK.NS", "ZFCVINDIA.NS", "ZEEL.NS", "ZENSARTECH.NS", "ZOMATO.NS",
                     "ZYDUSLIFE.NS", "ECLERX.NS"]

# Additional symbols provided by user
nifty_500_symbols.extend([
    "INNOTYRES.NS", "BALAJIPHOS.NS", "FAZETHREE.NS", "ASTRAMICRO.NS", "PURPLEUNITS.NS",
    "MANGCHEFER.NS", "PARADEEP.NS", "DHANUKAREALT.NS", "ZENTEC.NS", "SECMARK.NS",
    "KITEX.NS", "ABHIINT.NS", "CPSSHAPER.NS", "INDIAGLYCO.NS", "SHANTIOVERS.NS",
    "COFFEEDAY.NS", "LLOYDSLUX.NS", "CENTUM.NS", "ASHIMA.NS", "UTTAMSUGAR.NS",
    "SHEETALUNI.NS", "PRIVISCL.NS", "FORCEMOT.NS", "VASULOG.NS", "ELINEL.NS",
    "SPORTKING.NS", "NUCLEUS.NS", "ASAHISONG.NS", "JINDALPHOT.NS", "ANURAS.NS",
    "HITACHIEN.NS", "ECOSMOB.NS", "SARLAPERF.NS", "JPOLYINVST.NS", "AUTHUM.NS",
    "WANBURY.NS", "TERASOFT.NS", "CHOICEIN.NS", "TDPOWERSYS.NS", "KOLTEPATIL.NS",
    "KILITCH.NS", "RMDRIP.NS", "KRYSTAL.NS", "SILGO.NS", "TI.NS",
    "CUPID.NS", "SAHPOLY.NS", "SINDHUTRAD.NS", "WINDMACHIN.NS", "COUNTRYCON.NS",
    "BASILIC.NS", "URAVI.NS", "PANSARI.NS", "CARYSL.NS", "CONCORD.NS",
    "BOHRIND.NS", "BYKE.NS", "RAMCOSYS.NS", "VALIANTORG.NS", "TFCILTD.NS",
    "NAHARSPING.NS", "HOACFOODS.NS", "MANINDS.NS", "APTECHT.NS", "NDRAUTO.NS",
    "MAHSCOOTER.NS", "DANISHPOW.NS", "AZAD.NS", "AXISCADES.NS", "ALPEX.NS",
    "PARAGMILK.NS", "SUNDARMHLD.NS", "YUKEN.NS", "SANGHVIMOV.NS", "SSWL.NS",
    "SHANKARABUILD.NS", "KARNIKA.NS", "MYMUDRA.NS", "SHK.NS", "MEGASOFT.NS",
    "GOODLUCK.NS", "ASPIRE.NS", "MODIRUBBE.NS", "VESUVIUS.NS", "SURYAROSNI.NS",
    "ORIENTAROM.NS", "BLKASHYAP.NS", "THYROCARE.NS", "WAAREENG.NS", "GANINFRA.NS",
    "INFINPHARMA.NS", "ABDIST.NS", "NAHARPOLYF.NS", "MASTERTRUST.NS", "FOSECO.NS",
    "BUTTERFLY.NS", "MOREPENLABS.NS", "PRUDENT.NS", "AGARTOUG.NS", "FLAIR.NS",
    "INTERARCH.NS", "RACLGEAR.NS", "TATVA.NS", "GPECO.NS", "SWARAJSUIT.NS",
    "TVSHLTD.NS", "DREDGECORP.NS", "ANUHPHR.NS", "KRBL.NS", "INDIANCARD.NS",
    "UFLEX.NS", "BODAL.NS", "SCHAND.NS", "KAYA.NS", "VINYAS.NS",
    "NAHARINDUS.NS", "BIL.NS", "GABRIEL.NS", "MAXVOLT.NS", "ACMESOLAR.NS",
    "GEL.NS", "YATRA.NS", "MANORAMA.NS", "APOLLO.NS", "RPTECH.NS",
    "EIMCOELECO.NS", "KHAITANLTD.NS", "ROSSELLTECH.NS", "URJA.NS", "GRILL.NS",
    "SOLEXENERGY.NS", "INDPEST.NS", "TANKUP.NS", "DHARMAJ.NS", "PRECWIRE.NS",
    "VASCON.NS", "PRIZOR.NS", "IFGLEXPOR.NS", "DCX.NS", "BIRLANU.NS",
    "RALLIS.NS", "SHRIPISTON.NS", "MAHICKRA.NS", "ONESOURCE.NS", "DCBBANK.NS",
    "REPRO.NS", "ROTOPUMP.NS", "IOLCP.NS", "ARUNAYA.NS", "BALMLAWRIE.NS",
    "RANEMA.NS", "ISGEC.NS", "UNIVPHOTO.NS", "DHANUKA.NS", "MADRASFERT.NS",
    "STANDARDGL.NS", "PENIND.NS", "UNIHEALTH.NS", "VRLLOG.NS", "KHAITAN.NS",
    "SEL.NS", "ARIES.NS", "GENUSPOWER.NS", "GROBTEA.NS", "VSSSL.NS",
    "DIENSTEN.NS", "WHEELS.NS", "MASONINFRA.NS", "AARTISRF.NS", "AARON.NS",
    "VISIONINFRA.NS", "VISAKA.NS", "MASTER.NS", "NDTV.NS", "VAIDAA.NS",
    "THOMASCOOK.NS", "TNPL.NS", "AARTIDRUGS.NS", "BLSINFO.NS", "TALBROAUTO.NS",
    "DOCMODE.NS", "PRECOT.NS", "ZEELEARN.NS", "TECHNO.NS", "NRBBEARING.NS",
    "IRIS.NS", "SMSPHARMA.NS", "VINSYS.NS", "SUPREMEPET.NS", "CLSEL.NS",
    "LOTUSEYE.NS", "IXIGO.NS", "TVSELECT.NS", "INSPIRISYS.NS", "DLINK.NS",
    "RRW.NS", "ABANS.NS", "ITDCEM.NS", "HIRECT.NS", "TRANSTEEL.NS",
    "BANNARI.NS", "VILASTRANS.NS", "SANDUMA.NS", "SHARDACROP.NS", "SAGCEM.NS",
    "UNICOMMERCE.NS", "LUMAXTECH.NS", "AUSOM.NS", "KRITINDT.NS", "MOLDTKPAC.NS",
    "INTLCONV.NS", "LFIC.NS", "ANLONTECH.NS", "TOKYOPLAST.NS", "BALUFORGE.NS",
    "SEJAL.NS", "KRITIND.NS", "BHARATSEATS.NS", "EUREKAFORBE.NS", "GHCL-TEXT.NS",
    "ALEMBICLTD.NS", "LMW.NS", "MEDPLUS.NS", "LINC.NS", "PENLAND.NS",
    "IWEL.NS", "SAHYADRI.NS", "SKIPPER.NS", "WALCHANNAG.NS", "VOLTAMP.NS",
    "REMSONSIND.NS", "ZYDUSWELL.NS", "SANDHAR.NS", "HPLELEC.NS", "ABD.NS",
    "SPAPP.NS", "SHAILY.NS", "SHARDAMOTR.NS", "SONU.NS", "MTAR.NS",
    "NGLFINECHEM.NS", "SJS.NS", "CAMLINFINE.NS", "SABEVENT.NS", "VINNY.NS",
    "MAYURUNIQ.NS", "ORIENTPPR.NS", "VADIVARHE.NS", "BHARATGEAR.NS", "ORIANA.NS",
    "BURGERKING.NS", "RSWM.NS", "THINKHATE.NS", "JBMATO.NS", "GODAVARIBUS.NS",
    "SOUTHBANK.NS", "LUMAXIND.NS", "SYLVAN.NS", "MOHITIND.NS", "PIX.NS",
    "COMMITTED.NS", "COSMOFIRST.NS", "ELEGANZ.NS", "MROTEK.NS", "SDRETAIL.NS",
    "KALPATPOWR.NS", "JAYNECOIND.NS", "VISHMEGA.NS", "JHS.NS", "ZAGGLE.NS",
    "READYMIX.NS", "SETUBANDHAN.NS", "FIDEL.NS", "JAMNAAUTO.NS", "OPTIEMUS.NS",
    "BAJELPROJ.NS", "MEGASTAR.NS", "NATHBIOGEN.NS", "ORIENTLTD.NS", "MADHUMASALA.NS",
    "DVDGVIJAY.NS", "MOIL.NS", "DHARICORP.NS", "RELINFRA.NS", "HECINFRA.NS",
    "SBCEXPORT.NS", "JAKHARIA.NS", "PHOENIXOVS.NS", "GSMFOILS.NS", "SIGMASOLVE.NS",
    "POLYPLEX.NS", "ZOTA.NS", "JUBLAGRI.NS", "KPIGREEN.NS", "OSELDEVICES.NS",
    "MAHAMAYA.NS", "GAJANANN.NS", "APS.NS", "SPREF.NS", "MUNJALAU.NS",
    "PPAP.NS", "ZODIACLOTH.NS", "FIEMIND.NS", "MENONBE.NS", "GRP.NS",
    "SUBROS.NS", "AMBIKCO.NS", "ANYAFERTIL.NS", "AKSHAR.NS", "GANESHBHRT.NS",
    "VELSINTL.NS", "KAVVERITEL.NS", "FOCE.NS", "AARTIPHARMA.NS", "DWARKESH.NS",
    "TECHERA.NS", "SEQUENT.NS", "KIRIINDUS.NS", "AMJLAND.NS", "INGERRAND.NS",
    "PHANTOMFX.NS", "IBL.NS", "GKW.NS", "INDNIPPON.NS", "FDC.NS",
    "LUXIND.NS", "ROLLATAINERS.NS", "MUKANDLTD.NS", "63MOONS.NS", "SIXSIGMA.NS",
    "PCJEWELLER.NS", "CEREBRAINT.NS", "RAJRATAN.NS", "JAICORPLTD.NS", "DIVGI.NS",
    "BANKRAINTREE.NS", "STEELXIND.NS", "ALKALI.NS", "HOVS.NS", "JMA.NS",
    "MUNJALSHOW.NS", "BIRLACABLE.NS", "ALICON.NS", "VEEDOL.NS", "MUFIN.NS",
    "TII.NS", "VIPCIND.NS", "EUROFRESH.NS", "IPHOSPLT.NS", "INDIANIPPON.NS",
    "GLOBEINTL.NS", "NILKAMAL.NS", "MUKTAARTS.NS", "SHIVATEX.NS", "HINDWARE.NS",
    "SUPREMEPOW.NS", "KIOCL.NS", "INNOMET.NS", "MINDTECK.NS", "GEOJITFSL.NS",
    "ESABINDIA.NS", "CIGNITITECH.NS", "UNIVCABLES.NS", "AATMAJ.NS", "RATNAVEER.NS",
    "TECHNOCRAFT.NS", "AVITEX.NS", "BHAGERIA.NS", "TRANSRAIL.NS", "MOSUTILITIES.NS",
    "HMVL.NS", "CENTRUM.NS", "PATTECH.NS", "SMARTLINK.NS", "CADSYS.NS",
    "APCOTEXIND.NS", "VISAGLOBAL.NS", "TCIEXP.NS", "ROBUSTHOT.NS", "ONLIFECAP.NS",
    "AGIINFRA.NS", "FUSION.NS", "GLOBALEDU.NS", "ANTONY.NS", "TASTYBITE.NS",
    "AMBANIORG.NS", "EXWIRES.NS", "COMPUSOFT.NS", "LTFOODS.NS", "MARKSANS.NS",
    "GOKEX.NS", "PRAMARA.NS", "KAPSTON.NS", "ORTEL.NS", "GILLANDERS.NS",
    "ALLETHECH.NS", "STCINDIA.NS", "WABAG.NS", "HOLMARC.NS", "RAJCASS.NS",
    "STEELXIND.NS", "ATLAA.NS", "DIVGI.NS", "ZINKA.NS", "ISHANDYES.NS",
    "KAYCEEEN.NS", "SAURASHCEM.NS", "ASINGRAN.NS", "IONEXCHANG.NS", "MURUDCERA.NS",
    "KOTHARISUG.NS", "VRAJ.NS", "MAANLUM.NS", "KIRLOSIND.NS", "ELDEHSG.NS",
    "MAHALAXFABR.NS", "SHUBHSBIOE.NS", "ORICON.NS", "MAXEST.NS", "NAMOEWASTE.NS",
    "JAYSHREETEA.NS", "CYBERMEDIA.NS", "BLACKBOX.NS", "AVRO.NS", "LOKESHMACH.NS",
    "AVTIL.NS", "JITFINFRA.NS", "BHAGYANGR.NS", "TEAMLEASE.NS", "RAMASTEEL.NS",
    "GMMPFAUDLER.NS", "ABRETS.NS", "PARAGON.NS", "FUSIONRS5.NS", "RUPA.NS",
    "DPWIRES.NS", "MALUPAPER.NS", "KNAGRI.NS", "PRABHAEN.NS", "RSYSTEMS.NS",
    "SINTERCOM.NS", "MADHYAPR.NS", "SATIA.NS", "SVPGLOB.NS", "BPL.NS",
    "MARALOVER.NS", "KRISHIVAL.NS", "INDEMULSIF.NS", "TRACXN.NS", "JIWANRAM.NS",
    "MASKIN.NS", "EDELWEISS.NS", "UDS.NS", "AMIORG.NS", "MAHLIFE.NS",
    "LGBBROSLTD.NS", "SRESTHA.NS", "LEMERITE.NS", "KOTHARIPRO.NS", "SONABLW.NS",
    "SHIGAN.NS", "QVCEXPORTS.NS", "FOODSIN.NS", "VAIBHAVGBL.NS", "GOCOLORS.NS",
    "GOCLENG.NS", "MMPIL.NS", "SAFARI.NS", "TIRUFORG.NS", "DHUNSRITEA.NS",
    "PAVNAIND.NS", "IDEALTPT.NS", "PETROCARB.NS", "IFBAGROIND.NS", "HYUNDAIMOTR.NS",
    "ELECTFORC.NS", "MEDIASSIST.NS", "ASPINWALL.NS", "DREAMFOLKS.NS", "RDS.NS",
    "MADHYABHA.NS", "GREENLAM.NS", "AIONTECHSO.NS", "LAXMICOT.NS", "WESCARR.NS",
    "HTMEDIA.NS", "ESPIRITSTON.NS", "POPULARV.NS", "SIGNORIA.NS", "ADITULTRA.NS",
    "ANMOL.NS", "MPSLTD.NS", "DELTAMAGNT.NS", "BHANDARI.NS", "GUFICBIO.NS",
    "SATKARTAR.NS", "HEXAWARE.NS", "SUNDARMPON.NS", "GACMTECH.NS", "SADBHIN.NS",
    "A2ZINFRA.NS", "GAYAHWS.NS", "JAYAGROGN.NS", "DUDIGITL.NS", "INNOVANATH.NS",
    "NAMANINS.NS", "ACCORDSYN.NS", "SUNLITEREC.NS", "SHRADHAINFR.NS", "ABSMARINE.NS",
    "RJLLTD.NS", "JAICORP.NS", "SAKSOFT.NS", "WSINDUSTRI.NS", "SCLAYTON.NS",
    "USHAFIN.NS", "BEARDSELL.NS", "HRHNXTSRVC.NS", "ONWARDTEC.NS", "DIGIKORE.NS",
    "CRAYONS.NS", "MEGA.NS", "GVKPIL.NS", "SAJHOTELS.NS", "DIGISPICE.NS",
    "NAGREEKA.NS", "EXPLEO.NS", "INDSWFTLAB.NS", "SASTECH.NS", "SAHAJFASH.NS",
    "ARHAMTECH.NS", "TRANSWARR.NS", "NAGREEKCAP.NS", "LPSSEC.NS", "PEARLGLOBAL.NS",
    "PARAMDYE.NS", "PLADA.NS", "CUBEX.NS", "VISHNU.NS", "LAXMIGOLDRN.NS",
    "PRITISNC.NS", "DIGICONTENT.NS", "SHANTHALA.NS", "TAKE.NS", "SUBEXLTD.NS",
    "THOMASCOTT.NS", "AGUNIV.NS", "BAWEJASTU.NS", "HILTON.NS", "AKIIND.NS",
    "WEWIN.NS", "SHREEPUSHK.NS", "ANIINT.NS", "AVPINFRA.NS", "REFEX.NS",
    "INVENTURE.NS", "SURANISTL.NS", "SHAREINDIA.NS", "ADDICTIVE.NS", "NEWJAISA.NS",
    "TBICORN.NS", "TBO.NS", "AMBEYLAB.NS", "MANAV.NS", "TIJARIA.NS",
    "TEMBO.NS", "CAMTECH.NS", "ROXHITECH.NS", "VAKRANGEE.NS"
])


# Function to map symbol to sector
def map_symbol_to_sector(symbol):
    # Remove .NS suffix
    code = symbol.replace(".NS", "").upper()

    # Special cases with exact matches
    special_cases = {
        "ITC": "Fast-Moving Consumer Goods (FMCG)",
        "ONGC": "Oil & Gas",
        "NTPC": "Power & Utilities",
        "NHPC": "Power & Utilities",
        "COALINDIA": "Metals & Mining",
        "HINDALCO": "Metals & Mining",
        "HINDZINC": "Metals & Mining",
        "VEDL": "Metals & Mining",
        "SAIL": "Metals & Mining",
        "TATASTEEL": "Metals & Mining",
        "JSWSTEEL": "Metals & Mining",
        "ADANIENT": "Conglomerate",
        "RELIANCE": "Conglomerate",
        "BAJAJHLDNG": "Conglomerate",
        "ADANIPORTS": "Infrastructure",
        "ADANIPOWER": "Power & Utilities",
        "ADANIGREEN": "Renewable Energy",
        "ADANIENSOL": "Renewable Energy",
        "ATGL": "Oil & Gas",
        "IRCTC": "Hospitality & Tourism",
        "EASEMYTRIP": "Hospitality & Tourism",
        "MAHINDCIE": "Automobiles",
        "M&M": "Automobiles",
        "ASHOKLEY": "Automobiles",
        "BAJAJ-AUTO": "Automobiles",
        "EICHERMOT": "Automobiles",
        "HEROMOTOCO": "Automobiles",
        "MARUTI": "Automobiles",
        "TVSMOTOR": "Automobiles",
        "APOLLOTYRE": "Automobiles",
        "CEATLTD": "Automobiles",
        "MRF": "Automobiles",
        "BOSCHLTD": "Automobiles",
        "BHARATFORG": "Automobiles",
        "SONACOMS": "Automobiles",
        "SUNDRMFAST": "Automobiles",
        "BHARTIARTL": "Telecom",
        "IDEA": "Telecom",
        "TATACOMM": "Telecom",
        "TTML": "Telecom",
        "HFCL": "Telecom",
        "ITI": "Telecom",
        "NESTLEIND": "Fast-Moving Consumer Goods (FMCG)",
        "HINDUNILVR": "Fast-Moving Consumer Goods (FMCG)",
        "DABUR": "Fast-Moving Consumer Goods (FMCG)",
        "BRITANNIA": "Fast-Moving Consumer Goods (FMCG)",
        "MARICO": "Fast-Moving Consumer Goods (FMCG)",
        "TATACONSUM": "Fast-Moving Consumer Goods (FMCG)",
        "GODREJCP": "Fast-Moving Consumer Goods (FMCG)",
        "COLPAL": "Fast-Moving Consumer Goods (FMCG)",
        "EMAMILTD": "Fast-Moving Consumer Goods (FMCG)",
        "DMART": "Retail",
        "VBL": "Fast-Moving Consumer Goods (FMCG)",
        "UBL": "Fast-Moving Consumer Goods (FMCG)",
        "RADICO": "Fast-Moving Consumer Goods (FMCG)",
        "GLAXO": "Pharmaceuticals & Healthcare",
        "PGHH": "Pharmaceuticals & Healthcare",
        "SANOFI": "Pharmaceuticals & Healthcare",
        "PFIZER": "Pharmaceuticals & Healthcare",
        "AJANTPHARM": "Pharmaceuticals & Healthcare",
        "ALKEM": "Pharmaceuticals & Healthcare",
        "AUROPHARMA": "Pharmaceuticals & Healthcare",
        "BIOCON": "Pharmaceuticals & Healthcare",
        "CIPLA": "Pharmaceuticals & Healthcare",
        "DIVISLAB": "Pharmaceuticals & Healthcare",
        "DRREDDY": "Pharmaceuticals & Healthcare",
        "GLENMARK": "Pharmaceuticals & Healthcare",
        "LUPIN": "Pharmaceuticals & Healthcare",
        "NATCOPHARM": "Pharmaceuticals & Healthcare",
        "SUNPHARMA": "Pharmaceuticals & Healthcare",
        "TORNTPHARM": "Pharmaceuticals & Healthcare",
        "IPCALAB": "Pharmaceuticals & Healthcare",
        "LAURUSLABS": "Pharmaceuticals & Healthcare",
        "ZYDUSLIFE": "Pharmaceuticals & Healthcare",
        "ABB": "Capital Goods",
        "SIEMENS": "Capital Goods",
        "BHEL": "Capital Goods",
        "THERMAX": "Capital Goods",
        "VOLTAS": "Capital Goods",
        "HAVELLS": "Capital Goods",
        "CROMPTON": "Capital Goods",
        "VGUARD": "Capital Goods",
        "WHIRLPOOL": "Consumer Durables",
        "BLUESTARCO": "Consumer Durables",
        "AMBER": "Consumer Durables",
        "IFBIND": "Consumer Durables",
        "ORIENTELEC": "Consumer Durables",
        "BAYERCROP": "Agriculture & Agrochemicals",
        "UPL": "Agriculture & Agrochemicals",
        "RALLIS": "Agriculture & Agrochemicals",
        "DEEPAKFERT": "Agriculture & Agrochemicals",
        "GUJGASLTD": "Oil & Gas",
        "IOC": "Oil & Gas",
        "BPCL": "Oil & Gas",
        "PETRONET": "Oil & Gas",
        "GAIL": "Oil & Gas",
        "GSPL": "Oil & Gas",
        "ASTRAL": "Cement & Building Materials",
        "KAYNES": "Information Technology (IT)",
        "ZOMATO": "Consumer Services",
        "PAYTM": "Financial Services",
        "NAUKRI": "Information Technology (IT)",
        "INDIAMART": "Information Technology (IT)",
        "JUSTDIAL": "Information Technology (IT)",
        "ZENSARTECH": "Information Technology (IT)",
        "LTTS": "Information Technology (IT)",
        "MPHASIS": "Information Technology (IT)",
        "COFORGE": "Information Technology (IT)",
        "TECHM": "Information Technology (IT)",
        "INFY": "Information Technology (IT)",
        "TCS": "Information Technology (IT)",
        "WIPRO": "Information Technology (IT)",
        "HCLTECH": "Information Technology (IT)",
        "LATENTVIEW": "Information Technology (IT)",
        "PERSISTENT": "Information Technology (IT)",
        "INTELLECT": "Information Technology (IT)",
        "SONATSOFTW": "Information Technology (IT)",
        "CYIENT": "Information Technology (IT)",
        "TANLA": "Information Technology (IT)",
        "TATAELXSI": "Information Technology (IT)",
        "ZENTEC": "Information Technology (IT)",
        "APTECHT": "Information Technology (IT)",
        "AXISCADES": "Information Technology (IT)",
        "ANLONTECH": "Information Technology (IT)",
        "TERASOFT": "Information Technology (IT)",
        "MEGASOFT": "Information Technology (IT)",
        "SIGMASOLVE": "Information Technology (IT)",
        "SAKSOFT": "Information Technology (IT)",
        "CIGNITITECH": "Information Technology (IT)",
        "HEXAWARE": "Information Technology (IT)",
        "RSYSTEMS": "Information Technology (IT)",
        "MINDTECK": "Information Technology (IT)",
        "COMPUSOFT": "Information Technology (IT)",
        "INSPIRISYS": "Information Technology (IT)",
        "DLINK": "Information Technology (IT)",
        "TECHNO": "Information Technology (IT)",
        "IRIS": "Information Technology (IT)",
        "VINSYS": "Information Technology (IT)",
        "IXIGO": "Information Technology (IT)",
        "CEREBRAINT": "Information Technology (IT)",
        "GLOBALEDU": "Information Technology (IT)",
        "ZEELEARN": "Information Technology (IT)",
        "CRAYONS": "Information Technology (IT)",
        "ZAGGLE": "Information Technology (IT)",
        "TEAMLEASE": "Information Technology (IT)",
        "TECHNOCRAFT": "Information Technology (IT)",
        "SMARTLINK": "Information Technology (IT)",
        "CADSYS": "Information Technology (IT)",
        "VISAGLOBAL": "Information Technology (IT)",
        "DIGISPICE": "Information Technology (IT)",
        "DIGIKORE": "Information Technology (IT)",
        "DIGICONTENT": "Information Technology (IT)",
        "SUBEXLTD": "Information Technology (IT)",
        "INVENTURE": "Information Technology (IT)",
        "CAMTECH": "Information Technology (IT)",
        "ROXHITECH": "Information Technology (IT)",
        "VAKRANGEE": "Information Technology (IT)",
        "HIRECT": "Information Technology (IT)",
        "LUMAXTECH": "Information Technology (IT)",
        "AIONTECHSO": "Information Technology (IT)",
        "ALLETHECH": "Information Technology (IT)",
        "63MOONS": "Information Technology (IT)",
        "SIXSIGMA": "Information Technology (IT)",
        "GMMPFAUDLER": "Capital Goods",
        "ISGEC": "Capital Goods",
        "KEC": "Capital Goods",
        "KPITTECH": "Capital Goods",
        "TITAGARH": "Capital Goods",
        "JINDALSAW": "Capital Goods",
        "GRAPHITE": "Capital Goods",
        "CARBORUNIV": "Capital Goods",
        "TIMKEN": "Capital Goods",
        "SKFINDIA": "Capital Goods",
        "SCHAEFFLER": "Capital Goods",
        "GRINDWELL": "Capital Goods",
        "HITACHIEN": "Capital Goods",
        "ELECON": "Capital Goods",
        "ELGIEQUIP": "Capital Goods",
        "CUMMINSIND": "Capital Goods",
        "KSB": "Capital Goods",
        "SUZLON": "Renewable Energy",
        "WEBSOL": "Renewable Energy",
        "INOXWIND": "Renewable Energy",
        "OLECTRA": "Electric Vehicles (EVs)",
        "JUBLINGREA": "Agriculture & Agrochemicals",
        "PIIND": "Agriculture & Agrochemicals",
        "DEEPAKNTR": "Agriculture & Agrochemicals",
        "SRF": "Chemicals & Specialty Chemicals",
        "NAVINFLUOR": "Chemicals & Specialty Chemicals",
        "TATACHEM": "Chemicals & Specialty Chemicals",
        "GNFC": "Chemicals & Specialty Chemicals",
        "GSFC": "Chemicals & Specialty Chemicals",
        "COROMANDEL": "Chemicals & Specialty Chemicals",
        "FINCABLES": "Cables",
        "POLYCAB": "Cables",
        "KEI": "Cables",
        "APLAPOLLO": "Metals & Mining",
        "MANAPPURAM": "Financial Services",
        "MUTHOOTFIN": "Financial Services",
        "IIFL": "Financial Services",
        "MOTILALOFS": "Financial Services",
        "EDELWEISS": "Financial Services",
        "360ONE": "Financial Services",
        "BAJFINANCE": "Financial Services",
        "CHOLAFIN": "Financial Services",
        "SHRIRAMFIN": "Financial Services",
        "IBULHSGFIN": "Financial Services",
        "L&TFH": "Financial Services",
        "PFC": "Financial Services",
        "RECLTD": "Financial Services",
        "IRFC": "Financial Services",
        "IREDA": "Renewable Energy",
        "HUDCO": "Financial Services",
        "IRB": "Infrastructure",
        "GMRINFRA": "Infrastructure",
        "ADANIPORTS": "Infrastructure",
        "IRCON": "Infrastructure",
        "RVNL": "Infrastructure",
        "PNCINFRA": "Infrastructure",
        "HSCL": "Infrastructure",
        "NCC": "Infrastructure",
        "KNR": "Infrastructure"}


        stock_sector_dict = {
        # Original Nifty 500 mapping
        "360ONE.NS": "Banking & Financial Services (BFSI)",
        "3MINDIA.NS": "others",
        "ABB.NS": "Capital Goods",
        "ACC.NS": "Cement & Building Materials",
        "AIAENG.NS": "others",
        "APLAPOLLO.NS": "Metals & Mining",
        "AUBANK.NS": "Banking & Financial Services (BFSI)",
        "AADHARHFC.NS": "Banking & Financial Services (BFSI)",
        "AARTIIND.NS": "others",
        "AAVAS.NS": "others",
        "ZYDUSLIFE.NS": "Pharmaceuticals & Healthcare",
        "ECLERX.NS": "Information Technology (IT)",
        "INNOTYRES.NS": "Automobiles",
        "BALAJIPHOS.NS": "Chemicals & Specialty Chemicals",
        "FAZETHREE.NS": "Textiles",
        "ASTRAMICRO.NS": "Information Technology (IT)",
        "PURPLEUNITS.NS": "others",
        "MANGCHEFER.NS": "Chemicals & Specialty Chemicals",
        "PARADEEP.NS": "Logistics",
        "DHANUKAREALT.NS": "Real Estate & Construction",
        "ZENTEC.NS": "Information Technology (IT)",
        "SECMARK.NS": "Information Technology (IT)",
        "KITEX.NS": "Textiles",
        "ABHIINT.NS": "Information Technology (IT)",
        "CPSSHAPER.NS": "Capital Goods",
        "INDIAGLYCO.NS": "Agriculture & Agrochemicals",
        "SHANTIOVERS.NS": "others",
        "COFFEEDAY.NS": "Fast-Moving Consumer Goods (FMCG)",
        "LLOYDSLUX.NS": "others",
        "CENTUM.NS": "Capital Goods",
        "ASHIMA.NS": "Textiles",
        "UTTAMSUGAR.NS": "Sugar & Fertilizers",
        "SHEETALUNI.NS": "Metals & Mining",
        "PRIVISCL.NS": "others",
        "FORCEMOT.NS": "Automobiles",
        "VASULOG.NS": "Logistics",
        "ELINEL.NS": "Power & Utilities",
        "SPORTKING.NS": "Textiles",
        "NUCLEUS.NS": "Information Technology (IT)",
        "ASAHISONG.NS": "Consumer Durables",
        "JINDALPHOT.NS": "Renewable Energy",
        "ANURAS.NS": "others",
        "HITACHIEN.NS": "Capital Goods",
        "ECOSMOB.NS": "Information Technology (IT)",
        "SARLAPERF.NS": "Chemicals & Specialty Chemicals",
        "JPOLYINVST.NS": "Real Estate & Construction",
        "AUTHUM.NS": "Banking & Financial Services (BFSI)",
        "WANBURY.NS": "Pharmaceuticals & Healthcare",
        "TERASOFT.NS": "Information Technology (IT)",
        "CHOICEIN.NS": "others",
        "TDPOWERSYS.NS": "Power & Utilities",
        "KOLTEPATIL.NS": "Real Estate & Construction",
        "KILITCH.NS": "Pharmaceuticals & Healthcare",
        "RMDRIP.NS": "others",
        "KRYSTAL.NS": "others",
        "SILGO.NS": "others",
        "TI.NS": "others",
        "CUPID.NS": "others",
        "SAHPOLY.NS": "others",
        "SINDHUTRAD.NS": "Textiles",
        "WINDMACHIN.NS": "Capital Goods",
        "COUNTRYCON.NS": "others",
        "BASILIC.NS": "others",
        "URAVI.NS": "others",
        "PANSARI.NS": "others",
        "CARYSL.NS": "others",
        "CONCORD.NS": "others",
        "BOHRIND.NS": "others",
        "BYKE.NS": "Hospitality & Tourism",
        "RAMCOSYS.NS": "Information Technology (IT)",
        "VALIANTORG.NS": "others",
        "TFCILTD.NS": "Capital Goods",
        "NAHARSPING.NS": "Textiles",
        "HOACFOODS.NS": "Fast-Moving Consumer Goods (FMCG)",
        "MANINDS.NS": "others",
        "APTECHT.NS": "Information Technology (IT)",
        "NDRAUTO.NS": "Automobiles",
        "MAHSCOOTER.NS": "Automobiles",
        "DANISHPOW.NS": "Power & Utilities",
        "AZAD.NS": "others",
        "AXISCADES.NS": "Information Technology (IT)",
        "ALPEX.NS": "others",
        "PARAGMILK.NS": "Fast-Moving Consumer Goods (FMCG)",
        "SUNDARMHLD.NS": "others",
        "YUKEN.NS": "Capital Goods",
        "SANGHVIMOV.NS": "Automobiles",
        "SSWL.NS": "Automobiles",
        "SHANKARABUILD.NS": "Real Estate & Construction",
        "KARNIKA.NS": "others",
        "MYMUDRA.NS": "Banking & Financial Services (BFSI)",
        "SHK.NS": "others",
        "MEGASOFT.NS": "Information Technology (IT)",
        "GOODLUCK.NS": "others",
        "ASPIRE.NS": "others",
        "MODIRUBBE.NS": "others",
        "VESUVIUS.NS": "others",
        "SURYAROSNI.NS": "others",
        "ORIENTAROM.NS": "Chemicals & Specialty Chemicals",
        "BLKASHYAP.NS": "Real Estate & Construction",
        "THYROCARE.NS": "Pharmaceuticals & Healthcare",
        "WAAREENG.NS": "Power & Utilities",
        "GANINFRA.NS": "Infrastructure",
        "INFINPHARMA.NS": "Pharmaceuticals & Healthcare",
        "ABDIST.NS": "others",
        "NAHARPOLYF.NS": "others",
        "MASTERTRUST.NS": "Banking & Financial Services (BFSI)",
        "FOSECO.NS": "others",
        "BUTTERFLY.NS": "Consumer Durables",
        "MOREPENLABS.NS": "Pharmaceuticals & Healthcare",
        "PRUDENT.NS": "others",
        "AGARTOUG.NS": "others",
        "FLAIR.NS": "others",
        "INTERARCH.NS": "others",
        "RACLGEAR.NS": "Automobiles",
        "TATVA.NS": "others",
        "GPECO.NS": "others",
        "SWARAJSUIT.NS": "others",
        "TVSHLTD.NS": "others",
        "DREDGECORP.NS": "Infrastructure",
        "ANUHPHR.NS": "Pharmaceuticals & Healthcare",
        "KRBL.NS": "Fast-Moving Consumer Goods (FMCG)",
        "INDIANCARD.NS": "others",
        "UFLEX.NS": "Packaging",
        "BODAL.NS": "Chemicals & Specialty Chemicals",
        "SCHAND.NS": "others",
        "KAYA.NS": "Pharmaceuticals & Healthcare",
        "VINYAS.NS": "others",
        "NAHARINDUS.NS": "Textiles",
        "BIL.NS": "others",
        "GABRIEL.NS": "Automobiles",
        "MAXVOLT.NS": "Power & Utilities",
        "ACMESOLAR.NS": "Renewable Energy",
        "GEL.NS": "others",
        "YATRA.NS": "Hospitality & Tourism",
        "MANORAMA.NS": "Media & Entertainment",
        "APOLLO.NS": "others",
        "RPTECH.NS": "others",
        "EIMCOELECO.NS": "Capital Goods",
        "KHAITANLTD.NS": "others",
        "ROSSELLTECH.NS": "others",
        "URJA.NS": "Power & Utilities",
        "GRILL.NS": "others",
        "SOLEXENERGY.NS": "Renewable Energy",
        "INDPEST.NS": "Agriculture & Agrochemicals",
        "TANKUP.NS": "others",
        "DHARMAJ.NS": "Agriculture & Agrochemicals",
        "PRECWIRE.NS": "others",
        "VASCON.NS": "Real Estate & Construction",
        "PRIZOR.NS": "others",
        "IFGLEXPOR.NS": "others",
        "DCX.NS": "others",
        "BIRLANU.NS": "others",
        "RALLIS.NS": "Agriculture & Agrochemicals",
        "SHRIPISTON.NS": "Automobiles",
        "MAHICKRA.NS": "others",
        "ONESOURCE.NS": "others",
        "DCBBANK.NS": "Banking & Financial Services (BFSI)",
        "REPRO.NS": "Pharmaceuticals & Healthcare",
        "ROTOPUMP.NS": "Capital Goods",
        "IOLCP.NS": "Pharmaceuticals & Healthcare",
        "ARUNAYA.NS": "others",
        "BALMLAWRIE.NS": "others",
        "RANEMA.NS": "others",
        "ISGEC.NS": "Capital Goods",
        "UNIVPHOTO.NS": "others",
        "DHANUKA.NS": "Agriculture & Agrochemicals",
        "MADRASFERT.NS": "Agriculture & Agrochemicals",
        "STANDARDGL.NS": "Cement & Building Materials",
        "PENIND.NS": "others",
        "UNIHEALTH.NS": "Pharmaceuticals & Healthcare",
        "VRLLOG.NS": "Logistics",
        "KHAITAN.NS": "others",
        "SEL.NS": "others",
        "ARIES.NS": "others",
        "GENUSPOWER.NS": "Power & Utilities",
        "GROBTEA.NS": "Agriculture & Agrochemicals",
        "VSSSL.NS": "others",
        "DIENSTEN.NS": "others",
        "WHEELS.NS": "Automobiles",
        "MASONINFRA.NS": "Infrastructure",
        "AARTISRF.NS": "others",
        "AARON.NS": "others",
        "VISIONINFRA.NS": "Infrastructure",
        "VISAKA.NS": "Cement & Building Materials",
        "MASTER.NS": "others",
        "NDTV.NS": "Media & Entertainment",
        "VAIDAA.NS": "others",
        "THOMASCOOK.NS": "Hospitality & Tourism",
        "TNPL.NS": "Paper",
        "AARTIDRUGS.NS": "Pharmaceuticals & Healthcare",
        "BLSINFO.NS": "Information Technology (IT)",
        "TALBROAUTO.NS": "Automobiles",
        "DOCMODE.NS": "Healthcare",
        "PRECOT.NS": "Textiles",
        "ZEELEARN.NS": "Education",
        "TECHNO.NS": "Information Technology (IT)",
        "NRBBEARING.NS": "Capital Goods",
        "IRIS.NS": "Information Technology (IT)",
        "SMSPHARMA.NS": "Pharmaceuticals & Healthcare",
        "VINSYS.NS": "Information Technology (IT)",
        "SUPREMEPET.NS": "others",
        "CLSEL.NS": "others",
        "LOTUSEYE.NS": "Healthcare",
        "IXIGO.NS": "Hospitality & Tourism",
        "TVSELECT.NS": "Consumer Durables",
        "INSPIRISYS.NS": "Information Technology (IT)",
        "DLINK.NS": "Information Technology (IT)",
        "RRW.NS": "others",
        "ABANS.NS": "others",
        "ITDCEM.NS": "Cement & Building Materials",
        "HIRECT.NS": "Information Technology (IT)",
        "TRANSTEEL.NS": "Metals & Mining",
        "BANNARI.NS": "others",
        "VILASTRANS.NS": "others",
        "SANDUMA.NS": "others",
        "SHARDACROP.NS": "Agriculture & Agrochemicals",
        "SAGCEM.NS": "Cement & Building Materials",
        "UNICOMMERCE.NS": "Information Technology (IT)",
        "LUMAXTECH.NS": "Information Technology (IT)",
        "AUSOM.NS": "others",
        "KRITINDT.NS": "others",
        "MOLDTKPAC.NS": "Packaging",
        "INTLCONV.NS": "others",
        "LFIC.NS": "Banking & Financial Services (BFSI)",
        "ANLONTECH.NS": "Information Technology (IT)",
        "TOKYOPLAST.NS": "others",
        "BALUFORGE.NS": "Metals & Mining",
        "SEJAL.NS": "others",
        "KRITIND.NS": "others",
        "BHARATSEATS.NS": "Automobiles",
        "EUREKAFORBE.NS": "others",
        "GHCL-TEXT.NS": "Textiles",
        "ALEMBICLTD.NS": "Pharmaceuticals & Healthcare",
        "LMW.NS": "Textiles",
        "MEDPLUS.NS": "Pharmaceuticals & Healthcare",
        "LINC.NS": "others",
        "PENLAND.NS": "others",
        "IWEL.NS": "Power & Utilities",
        "SAHYADRI.NS": "Cement & Building Materials",
        "SKIPPER.NS": "Power & Utilities",
        "WALCHANNAG.NS": "Cement & Building Materials",
        "VOLTAMP.NS": "Power & Utilities",
        "REMSONSIND.NS": "others",
        "ZYDUSWELL.NS": "Pharmaceuticals & Healthcare",
        "SANDHAR.NS": "Automobiles",
        "HPLELEC.NS": "others",
        "ABD.NS": "others",
        "SPAPP.NS": "others",
        "SHAILY.NS": "others",
        "SHARDAMOTR.NS": "Automobiles",
        "SONU.NS": "others",
        "MTAR.NS": "Capital Goods",
        "NGLFINECHEM.NS": "Chemicals & Specialty Chemicals",
        "SJS.NS": "others",
        "CAMLINFINE.NS": "Paper",
        "SABEVENT.NS": "others",
        "VINNY.NS": "others",
        "MAYURUNIQ.NS": "others",
        "ORIENTPPR.NS": "Paper",
        "VADIVARHE.NS": "Healthcare",
        "BHARATGEAR.NS": "Capital Goods",
        "ORIANA.NS": "others",
        "BURGERKING.NS": "Consumer Services",
        "RSWM.NS": "Textiles",
        "THINKHATE.NS": "others",
        "JBMATO.NS": "Automobiles",
        "GODAVARIBUS.NS": "Automobiles",
        "SOUTHBANK.NS": "Banking & Financial Services (BFSI)",
        "LUMAXIND.NS": "Automobiles",
        "SYLVAN.NS": "others",
        "MOHITIND.NS": "others",
        "PIX.NS": "others",
        "COMMITTED.NS": "others",
        "COSMOFIRST.NS": "Textiles",
        "ELEGANZ.NS": "others",
        "MROTEK.NS": "others",
        "SDRETAIL.NS": "others",
        "KALPATPOWR.NS": "Power & Utilities",
        "JAYNECOIND.NS": "Metals & Mining",
        "VISHMEGA.NS": "Information Technology (IT)",
        "JHS.NS": "others",
        "ZAGGLE.NS": "Information Technology (IT)",
        "READYMIX.NS": "Cement & Building Materials",
        "SETUBANDHAN.NS": "Infrastructure",
        "FIDEL.NS": "others",
        "JAMNAAUTO.NS": "Automobiles",
        "OPTIEMUS.NS": "Information Technology (IT)",
        "BAJELPROJ.NS": "others",
        "MEGASTAR.NS": "others",
        "NATHBIOGEN.NS": "Pharmaceuticals & Healthcare",
        "ORIENTLTD.NS": "others",
        "MADHUMASALA.NS": "others",
        "DVDGVIJAY.NS": "others",
        "MOIL.NS": "Metals & Mining",
        "DHARICORP.NS": "others",
        "RELINFRA.NS": "Infrastructure",
        "HECINFRA.NS": "Infrastructure",
        "SBCEXPORT.NS": "others",
        "JAKHARIA.NS": "others",
        "PHOENIXOVS.NS": "others",
        "GSMFOILS.NS": "Metals & Mining",
        "SIGMASOLVE.NS": "Information Technology (IT)",
        "POLYPLEX.NS": "Packaging",
        "ZOTA.NS": "Healthcare",
        "JUBLAGRI.NS": "Agriculture & Agrochemicals",
        "KPIGREEN.NS": "Renewable Energy",
        "OSELDEVICES.NS": "Information Technology (IT)",
        "MAHAMAYA.NS": "others",
        "GAJANANN.NS": "others",
        "APS.NS": "others" }